package com.skillexchange.notification;

public enum NotificationType {
    MATCH_REQUEST_RECEIVED, MATCH_ACCEPTED, MATCH_REJECTED, SESSION_BOOKED, SESSION_REMINDER,
    SESSION_CANCELLED, NEW_RATING_RECEIVED, BADGE_EARNED, NEW_MESSAGE_RECEIVED, RATE_SESSION
}
