import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff, Lock, Mail, Network, Sparkles, Users } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';

const schema = z.object({ email: z.string().email('Enter a valid email'), password: z.string().min(1, 'Password is required') });
function AuthArt() { return <div className="hidden flex-1 flex-col justify-center p-12 text-white lg:flex"><div className="max-w-lg"><div className="mb-8 inline-flex rounded-2xl bg-white/15 p-4"><Sparkles size={34}/></div><h1 className="font-display text-5xl font-extrabold leading-tight">Exchange skills. Grow together.</h1><p className="mt-5 text-lg text-purple-100">Find peers who teach what you want to learn, and trade knowledge with people who value what you know.</p><div className="mt-8 space-y-4"><p className="flex items-center gap-3"><Users/> AI-ranked peer learning partners</p><p className="flex items-center gap-3"><Network/> Real-time chat and session planning</p><p className="flex items-center gap-3"><Lock/> Secure JWT protected experience</p></div></div></div>; }
export default function LoginPage() { const [show,setShow]=useState(false); const { loginMutation } = useAuth(); const { register, handleSubmit, formState:{errors} } = useForm({ resolver: zodResolver(schema) }); return <main className="auth-shell flex min-h-screen"><div className="m-4 hidden flex-1 overflow-hidden rounded-[2rem] bg-gradient-to-br from-purple-700 via-indigo-600 to-blue-600 shadow-glow lg:flex"><AuthArt/></div><section className="flex flex-1 items-center justify-center p-6"><form onSubmit={handleSubmit((v)=>loginMutation.mutate(v))} className="w-full max-w-md rounded-3xl border border-white/70 bg-white/90 p-8 shadow-glow backdrop-blur"><h2 className="font-display text-4xl font-extrabold text-gray-900">Welcome back</h2><p className="mt-2 text-gray-500">Sign in to continue learning with your community.</p><label className="mt-8 block text-sm font-bold">Email<input className="input mt-2" {...register('email')} placeholder="alice@example.com" /></label>{errors.email && <p className="mt-1 text-sm text-red-500">{errors.email.message}</p>}<label className="mt-4 block text-sm font-bold">Password<div className="relative mt-2"><input type={show?'text':'password'} className="input pr-11" {...register('password')} placeholder="password123"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-2.5 text-gray-400">{show?<EyeOff/>:<Eye/>}</button></div></label>{errors.password && <p className="mt-1 text-sm text-red-500">{errors.password.message}</p>}<button disabled={loginMutation.isPending} className="btn-primary mt-6 w-full">{loginMutation.isPending ? 'Signing in...' : 'Sign In'}</button><p className="mt-6 text-center text-sm text-gray-500">New here? <Link to="/register" className="font-bold text-purple-600">Create an account</Link></p></form></section></main>; }