import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Eye, EyeOff, MapPin, Sparkles } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';

const schema = z.object({ fullName: z.string().min(2, 'Name must be at least 2 characters'), email: z.string().email('Enter a valid email'), password: z.string().min(8, 'Password must be at least 8 characters'), confirmPassword: z.string(), location: z.string().optional(), bio: z.string().max(200, 'Bio must be 200 characters or less').optional() }).refine((d)=>d.password===d.confirmPassword,{ message:'Passwords must match', path:['confirmPassword'] });
export default function RegisterPage(){ const [show,setShow]=useState(false); const { registerMutation }=useAuth(); const { register, handleSubmit, watch, formState:{errors} }=useForm({ resolver:zodResolver(schema) }); const submit=(v)=>registerMutation.mutate({ email:v.email, password:v.password, fullName:v.fullName, location:v.location, bio:v.bio }); return <main className="auth-shell flex min-h-screen"><div className="m-4 hidden flex-1 rounded-[2rem] bg-gradient-to-br from-purple-700 via-indigo-600 to-blue-600 p-12 text-white shadow-glow lg:block"><div className="flex h-full max-w-xl flex-col justify-center"><Sparkles size={42}/><h1 className="mt-8 font-display text-5xl font-extrabold">Start swapping knowledge today.</h1><p className="mt-5 text-lg text-purple-100">List what you teach, choose what you want to learn, and let SkillSwap surface people who fit.</p><div className="mt-8 rounded-2xl bg-white/10 p-5"><p className="font-bold">Your first match can happen in minutes.</p><p className="mt-2 text-sm text-purple-100">Add one teaching skill and one learning goal after registration.</p></div></div></div><section className="flex flex-1 items-center justify-center p-6"><form onSubmit={handleSubmit(submit)} className="w-full max-w-lg rounded-3xl border border-white/70 bg-white/90 p-8 shadow-glow"><h2 className="font-display text-4xl font-extrabold">Create account</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold md:col-span-2">Full Name<input className="input mt-2" {...register('fullName')} /></label><label className="text-sm font-bold md:col-span-2">Email<input className="input mt-2" {...register('email')} /></label><label className="text-sm font-bold">Password<div className="relative mt-2"><input type={show?'text':'password'} className="input pr-10" {...register('password')} /><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-2.5 text-gray-400">{show?<EyeOff/>:<Eye/>}</button></div></label><label className="text-sm font-bold">Confirm Password<input type="password" className="input mt-2" {...register('confirmPassword')} /></label><label className="text-sm font-bold md:col-span-2">Location<input className="input mt-2" {...register('location')} placeholder="Chennai, Remote, Bengaluru..." /></label><label className="text-sm font-bold md:col-span-2">Brief Bio<textarea className="input mt-2" rows="3" maxLength="200" {...register('bio')} /></label></div>{Object.values(errors)[0] && <p className="mt-3 text-sm text-red-500">{Object.values(errors)[0].message}</p>}<button disabled={registerMutation.isPending} className="btn-primary mt-6 w-full">{registerMutation.isPending?'Creating account...':'Register'}</button><p className="mt-5 text-center text-sm text-gray-500">Already have an account? <Link className="font-bold text-purple-600" to="/login">Sign in</Link></p></form></section></main>; }