import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { Camera } from 'lucide-react';
import { updateMe } from '../../api/user.api';
import { useAuth } from '../../hooks/useAuth';
import UserAvatar from '../../components/common/UserAvatar';

const schema=z.object({fullName:z.string().min(2).max(255).optional(),headline:z.string().max(255).optional(),bio:z.string().max(200).optional(),languages:z.string().max(500).optional(),location:z.string().max(255).optional(),linkedinUrl:z.string().max(500).optional(),profilePictureUrl:z.string().max(500).optional()});
export default function EditProfilePage(){ const { currentUser, updateUser }=useAuth(); const nav=useNavigate(); const qc=useQueryClient(); const [preview,setPreview]=useState(currentUser?.profilePictureUrl||''); const {register,handleSubmit,watch,formState:{errors}}=useForm({resolver:zodResolver(schema),defaultValues:currentUser||{}}); const bio=watch('bio')||''; const mutation=useMutation({mutationFn:updateMe,onSuccess:(u)=>{updateUser(u);qc.invalidateQueries({queryKey:['user','me']});toast.success('Profile saved!');nav('/profile');},onError:e=>toast.error(e.response?.data?.message||'Could not save profile')}); return <div className="mx-auto max-w-3xl"><form onSubmit={handleSubmit((v)=>mutation.mutate({...v,profilePictureUrl:preview||v.profilePictureUrl}))} className="card"><h1 className="font-display text-4xl font-extrabold">Edit profile</h1><p className="mt-2 text-gray-500">Keep your public learning identity clear and trustworthy.</p><div className="mt-8 flex items-center gap-5"><UserAvatar user={{...currentUser,profilePictureUrl:preview}} size="lg"/><label className="btn-secondary cursor-pointer"><Camera size={16} className="mr-2 inline"/>Use image URL<input className="sr-only" onChange={()=>{}} /></label></div><label className="mt-6 block text-sm font-bold">Profile picture URL<input className="input mt-2" {...register('profilePictureUrl')} onChange={(e)=>setPreview(e.target.value)} /></label><label className="mt-4 block text-sm font-bold">Full Name<input className="input mt-2" {...register('fullName')} /></label><label className="mt-4 block text-sm font-bold">Headline — what can you help with?<input className="input mt-2" placeholder="e.g. Full-stack dev happy to mentor in React & Node" {...register('headline')} /></label><label className="mt-4 block text-sm font-bold">Bio<textarea className="input mt-2" rows="5" maxLength="200" {...register('bio')} /></label><p className="text-right text-xs text-gray-400">{bio.length}/200</p><label className="mt-4 block text-sm font-bold">Languages spoken<input className="input mt-2" placeholder="e.g. English, Tamil, Hindi" {...register('languages')} /></label><label className="mt-4 block text-sm font-bold">Location<input className="input mt-2" {...register('location')} /></label><label className="mt-4 block text-sm font-bold">LinkedIn URL<input className="input mt-2" {...register('linkedinUrl')} /></label>{Object.values(errors)[0]&&<p className="mt-3 text-sm text-red-500">{Object.values(errors)[0].message}</p>}<div className="mt-6 flex justify-end gap-2"><Link className="btn-secondary" to="/profile">Cancel</Link><button disabled={mutation.isPending} className="btn-primary">{mutation.isPending?'Saving...':'Save Changes'}</button></div></form></div>; }